import Head from 'next/head'
import styles from './index.module.scss'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.container__test1}>練習用サイトeee</div>
        <div className={styles.container__test2}>練習用サイト2aaa</div>
      </div>
    </>
  )
}
