import Head from 'next/head'
import styles from './index.module.scss'
import {useState} from "react";


export default function Home() {
  const [name, setName] = useState("");
  const [isDisplayName, setIsDisplayName] = useState(false);

  console.log("---loop---");
  console.log(name);
  console.log(isDisplayName);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.container__test1}>練習用</div>
        <div className={styles.container__test2}>練習用サイト2</div>
        <input className={styles.container__input} placeholder="ここに名前を入力してください" value={name} onChange={(event) => setName(event.target.value)} />
        <button onClick={() => setIsDisplayName(!isDisplayName)} className={styles.container__button}>ボタンを押したら名前表示非表示切り替え</button>
        {isDisplayName && <div className={styles.container__name}>{name}</div>}
        <div className={styles.container__box}>
          <div className={styles.container__box__text1}>プログラミングで</div>
          <div className={styles.container__box__text1}>人生の安定と収入を手に入れよう</div>
        </div>
      </div>
      <div className={styles.test}>奏志記録 サンプルページ</div>
      <img src="奏志七五三画像.jpeg" alt="奏志七五三画像" width="200" />
      <div>奏志写真集</div> 
      <p>
      岡山県在住<br />
      両親と１歳の妹と仲良く暮らしています。</p>
            <br />
            <div>奏志くん生年月日 2018年10月9日生まれ A型 天秤座</div>
      <div>現在は４歳でパズルとベビーバスを観るのが大好きです</div>
    </>
    
  )
}
