import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react';

type Person = {
  name: string;
  age: number;
  note: string;
  registerDate: string;
};

const Study: NextPage = () => {
  const router = useRouter();

  const { isLoading, error, data } = useQuery({
    queryKey: ['repoData'],
    queryFn: () =>
      axios.get('https://umayadia-apisample.azurewebsites.net/api/persons').then((res) => res),
  });
  console.log(isLoading);
  console.log(data);
  console.log(error);

  return (
    <>
      <Head>
        <title>日々の課題</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <button onClick={() => router.push('http://localhost:3000/')}>元ページへ</button>
    </>
  );
};

export default Study;
